import React, { useState, useEffect } from 'react';
import api from '../../api/axiosClient';

export function ConsumerRecipes() {
  const [pantryItems, setPantryItems] = useState([]);
  const [recipes, setRecipes] = useState([]);
  const [generating, setGenerating] = useState(false);

  const fetchPantryAndGenerateRecipes = async () => {
    setGenerating(true);
    try {
      const { data } = await api.get('/inventory', { params: { status: 'active' } });
      const items = Array.isArray(data) ? data : [];
      setPantryItems(items);
      const ingredientNames = items.map((i) => i.foodName).filter(Boolean);
      if (ingredientNames.length > 0) {
        const res = await api.post('/chat/recipes/generate', { ingredients: ingredientNames });
        setRecipes(res.data?.recipes || []);
      }
    } catch {
      setRecipes([]);
    } finally {
      setGenerating(false);
    }
  };

  useEffect(() => { fetchPantryAndGenerateRecipes(); }, []);

  return (
    <div className="space-y-6 fade-up">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
        <div>
          <h1 className="text-2xl sm:text-3xl font-extrabold text-white flex items-center gap-2"><span>🍳</span> AI Recipe Suggestions</h1>
          <p className="text-slate-400 text-xs sm:text-sm mt-1">Zero-waste recipe ideas generated by Gemini AI for your fridge stock.</p>
        </div>
        <button onClick={fetchPantryAndGenerateRecipes} disabled={generating} className="btn-glow px-4 py-2.5 rounded-xl text-white text-xs font-semibold self-start sm:self-auto">
          {generating ? <span className="spinner" /> : '✨ Regenerate'}
        </button>
      </div>

      {generating ? (
        <div className="glass p-12 text-center text-slate-300 rounded-2xl animate-pulse">Gemini AI is crafting your recipes...</div>
      ) : recipes.length === 0 ? (
        <div className="glass p-12 text-center text-slate-400 rounded-2xl">No recipes found. Add items to your fridge!</div>
      ) : (
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          {recipes.map((r, idx) => (
            <div key={idx} className="glass p-5 rounded-2xl border border-white/10 space-y-3 hover:border-emerald-500/30 transition-all">
              <h3 className="font-bold text-white text-lg">{r.name}</h3>
              <p className="text-xs text-slate-400">⏱ {r.time || '15 min'} · {r.difficulty || 'Easy'}</p>
              <div className="flex flex-wrap gap-1">
                {(r.uses || []).map((u, i) => <span key={i} className="text-[10px] px-2 py-0.5 bg-white/10 rounded text-slate-300">{u}</span>)}
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
